import { identityDetails } from './identity';
export type Detail = { kicker: string; title: string; lead: string; paragraphs: string[]; tags: string[]; bullets?: string[]; note?: string };
const archiveDetails: Record<string, Detail> = {
  rogue: { kicker: 'FOUNDER / ROGUE LIBERATION', title: 'Building a brand from zero.', lead: 'A clothing brand, and an early experience of making a business tangible.', paragraphs: ['Rogue Liberation brought together design, production, and brand identity. It is part of the founder experience behind The Anti Matrix Project.'], tags:['Design','Production','Brand identity'] },
  pine: { kicker:'FIELD NOTE / PINE & THATCH', title:'The work behind the stay.', lead:'Hospitality brings a business into sharp focus: demand, people, place, and the experience guests actually have.', paragraphs:['The published Pine & Thatch story describes work with an 18-room hill hotel in Mashobra, Shimla: booking channels, local demand, pricing, staffing, vendors, renovations, and operating procedures.','This is the business-operations side of Anti Matrix: connecting the commercial picture to the work happening on the ground.'], tags:['Hospitality','Bookings','Operating procedures','Demand'], note:'Scene artwork is illustrative.' },
  influcreate: { kicker:'FOUNDER / INFLUCREATE', title:'Connecting brands and creators.', lead:'Creator marketing is also an operating problem: bringing the right people, briefs, and expectations together.', paragraphs:['Influcreate is part of Gurman’s founder journey, with work around brand–creator collaboration and marketing coordination.'], tags:['Creator marketing','Collaboration','Coordination'] },
  operations: { kicker:'BUSINESS OPERATIONS / ZELTO (ADPUSHUP)', title:'Understand the relationships.', lead:'Gurman joined the CEO’s team, working across business operations, data systems, and strategic frameworks.', paragraphs:['The existing story also covers operating cadence, hiring, internal knowledge, reporting, and investor communication. These are connected responsibilities: the information a team has shapes the decisions it can make.','The aim is a useful relationship between strategy and everyday execution, whether the answer is a clearer process, a better source of information, or a tool.'], tags:['Business operations','Knowledge systems','Reporting','Strategic frameworks'] },
  tenant: { kicker:'PERSONAL BUILD / TENANT MANAGEMENT', title:'From a physical ledger to a clearer picture.', lead:'A tool for tenant records, utility calculations, ledger updates, and receipts.', paragraphs:['This experiment translates familiar property-management work into a visual interface. The operating context comes first: keep records together, make routine calculations easier, and make receipts accessible.','It is part of an ongoing practice of turning everyday friction into something useful.'], tags:['Property operations','Tenant ledger','Utility calculations','Receipts'], note:'Stage: Beta Active' },
  maos: { kicker:'PERSONAL BUILD / MAOS', title:'Getting different models to work together.', lead:'An exploration of routing work between local and cloud AI models.', paragraphs:['MAOS stands for Multi-Agent Operating System. Its place in the archive is an ongoing orchestration experiment: how work can be directed across a mixed toolkit.','Different models bring different strengths. This project explores how they can contribute to a shared workflow.'], tags:['AI orchestration','Local models','Cloud models'], note:'Stage: Active Engineering' },
  pdf: { kicker:'PERSONAL BUILD / PDF APP', title:'The information is already in there.', lead:'A document-processing tool for extracting information from business, tax, and land records.', paragraphs:['The project explores local document processing and the practical work of turning source documents into usable information.','The key question is operational: how can a repetitive document task become easier to complete and check?'], tags:['Documents','Extraction','Local processing'], note:'Stage: Active Use' },
  dev: { kicker:'PERSONAL BUILD / DEV SQUAD', title:'Keep the work connected.', lead:'An experiment in coordinating developer tasks, progress, GitHub workflows, and Obsidian documentation.', paragraphs:['Dev Squad explores how the context around building can stay connected: what needs doing, what changed, and where the supporting knowledge lives.'], tags:['Coordination','GitHub','Documentation'], note:'Stage: Beta Active' },
  pos: { kicker:'FIELD BUILD / RESTAURANT ANDROID POS', title:'Software meets the floor.', lead:'A tablet point-of-sale build around billing, table layout, and restaurant workflows.', paragraphs:['An order is one part of a larger operating loop: know the table, record the order, settle the bill, and produce the receipt.','The project explores offline transactions, printing, and synchronization across a restaurant tablet and its connected devices.'], tags:['Restaurant operations','Android','Billing','Table workflows'], note:'Project study. The gallery artwork is a conceptual illustration of the workflow.' },
  revlift: { kicker:'IN DEVELOPMENT / REVLIFT', title:'The system behind the ad.', lead:'Mobile header bidding, connected to publisher operations.', paragraphs:['Revlift brings together an Android SDK, a publisher control plane, auction workflows, and reporting.','The work connects app integration and ad delivery with configuration, fallback handling, and operational visibility. It is an AdTech build shaped by the needs of the people operating it.'], tags:['AdTech','Android SDK','Header bidding','Publisher operations'], note:'In development. The gallery artwork illustrates the system; it does not represent measured revenue results.' },
  hiring: { kicker:'FIELD NOTE / TEAM SYSTEMS', title:'Before the next hire.', lead:'The 4 Frameworks Every Startup Should Build Before Hiring.', paragraphs:['The existing essay explores role documentation, operating cadence, handoffs, and internal knowledge. These establish the context a new team member needs to contribute.','A good operating framework should make responsibilities and decisions clearer without adding unnecessary overhead.'],tags:['Hiring','Handoffs','Operating cadence'],note:'A short introduction to an existing essay. The full published writing is available in the current Control Deck.' },
  reporting: { kicker:'FIELD NOTE / REPORTING', title:'Make the picture easier to read.', lead:'How Post-Investment Founders Can Build Reporting Systems Investors Love.', paragraphs:['The existing essay brings together source-of-truth data, financial reporting, ingestion workflows, and board materials. The focus is the relationship between information and a useful conversation.'],tags:['Reporting','Business information','Investor communication'],note:'Read the complete essay in the existing Control Deck.' },
  knowledge: { kicker:'FIELD NOTE / KNOWLEDGE', title:'Give knowledge somewhere to live.', lead:'Why Every Startup Needs an Internal Knowledge Base Before Scaling.', paragraphs:['The existing essay explores structured knowledge, connected documentation, standard operating procedures, and documentation habits.','The practical goal is to make important context accessible beyond the person who currently holds it.'],tags:['Knowledge systems','SOPs','Documentation'] }
};
export const projects = [ ['tenant','Tenant Management','Ledgers, utilities, and receipts'], ['maos','MAOS','Local and cloud model orchestration'], ['pdf','Document Intelligence','Local document-processing experiment'], ['pos','Restaurant POS','Android billing and restaurant workflows'], ['revlift','Revlift','Mobile header bidding and publisher operations'], ['dev','Dev Squad','Tasks, progress, and documentation'] ];
export const notes = [ ['hiring','Before the next hire','Role clarity, cadence, and handoffs'], ['reporting','A clearer reporting system','Business information and investor communication'], ['knowledge','Knowledge that stays connected','Documentation, SOPs, and team habits'], ['pine','The work behind the stay','The Pine & Thatch operating story'] ];
export const details: Record<string, Detail> = {...archiveDetails, ...identityDetails};
export const music = [
 {title:'Pahaadon Ki Yaadein',date:'Sep 2024',genre:'Acoustic Hindi / Himachali folk',recordings:[
  {label:'Original',file:'pahaadon-ki-yaadein.mp3'},
  {label:'Alternate take',file:'pahaadon-ki-yaadein-alt.mp3'}
 ]},
 {title:'The Light',date:'Nov 2025',genre:'Nu metal / rap / soft chorus rock',recordings:[{label:'Listen',file:'the-light.mp3'}]},
 {title:'Chhota Sa Tan',date:'Feb 2026',genre:'Heavy metal with Indian classical vocals',recordings:[{label:'Listen',file:'chhota-sa-tan.mp3'}]},
 {title:'Oonchai Pe Thandi Hawa',date:'Feb 2026',genre:'Heavy metal with Indian classical vocals',recordings:[{label:'Listen',file:'oonchai-pe-thandi-hawa.mp3'}]},
 {title:'Floors of the Same Church',date:'Apr 2026',genre:'Folk / indie folk / ambient',recordings:[{label:'Listen',file:'floors-of-the-same-church.mp3'}]}
] as const;
export const toolkit = [
  {label:'01 / THINK',title:'Explore a question.',tools:['OpenAI','Claude','Gemini','Local models']},
  {label:'02 / BUILD',title:'Give it a form.',tools:['Antigravity','Codex','Claude Code','Cursor / Windsurf']},
  {label:'03 / CONNECT',title:'Join the moving parts.',tools:['MAOS','Supabase','n8n','db_api_integrity']}
];
